api_hello request being processed
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1370, in handle_user_exception
    return self.handle_http_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1330, in handle_http_exception
    return handler(e)
  File "EventDetectionWebServer.py", line 112, in not_found
    resp.status_code = 404
AttributeError: 'str' object has no attribute 'status_code'
api_hello request being processed
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1370, in handle_user_exception
    return self.handle_http_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1330, in handle_http_exception
    return handler(e)
  File "EventDetectionWebServer.py", line 112, in not_found
    resp.status_code = 404
AttributeError: 'str' object has no attribute 'status_code'
api_hello request being processed
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1370, in handle_user_exception
    return self.handle_http_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1330, in handle_http_exception
    return handler(e)
  File "EventDetectionWebServer.py", line 112, in not_found
    resp.status_code = 404
AttributeError: 'str' object has no attribute 'status_code'
api_hello request being processed
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1370, in handle_user_exception
    return self.handle_http_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1330, in handle_http_exception
    return handler(e)
  File "EventDetectionWebServer.py", line 113, in not_found
    resp.status_code = 404
AttributeError: 'str' object has no attribute 'status_code'
api_hello request being processed
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1370, in handle_user_exception
    return self.handle_http_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1330, in handle_http_exception
    return handler(e)
  File "EventDetectionWebServer.py", line 145, in not_found
    resp.status_code = 404
AttributeError: 'str' object has no attribute 'status_code'
predict request being processed
Exception on /predict [POST]
Traceback (most recent call last):
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "EventDetectionWebServer.py", line 102, in process_predict
    email_manager.send_email.delay(user_email, youtube_url, [])
AttributeError: 'function' object has no attribute 'delay'
predict request being processed
Exception on /predict [POST]
Traceback (most recent call last):
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "EventDetectionWebServer.py", line 102, in process_predict
    email_manager.send_email.delay(user_email, youtube_url, [])
AttributeError: 'function' object has no attribute 'delay'
predict request being processed
Exception on /predict [POST]
Traceback (most recent call last):
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "EventDetectionWebServer.py", line 102, in process_predict
    email_manager.send_email(user_email, youtube_url, [])
  File "/Users/danielmacario/PycharmProjects/EventDetectionWebServer/mailmanager.py", line 13, in send_email
    self.mail.send(msg)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask_mail.py", line 192, in send
    message.rcpt_options)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 731, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
SMTPSenderRefused: (530, '5.5.1 Authentication Required. Learn more at\n5.5.1  https://support.google.com/mail/answer/14257 ki7sm217253igb.2 - gsmtp', u'eventdetectionmcgill@gmail.com')
predict request being processed
Exception on /predict [POST]
Traceback (most recent call last):
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "EventDetectionWebServer.py", line 103, in process_predict
    email_manager.send_email(user_email, youtube_url, [])
  File "/Users/danielmacario/PycharmProjects/EventDetectionWebServer/mailmanager.py", line 13, in send_email
    self.mail.send(msg)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask_mail.py", line 192, in send
    message.rcpt_options)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 731, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
SMTPSenderRefused: (530, '5.5.1 Authentication Required. Learn more at\n5.5.1  https://support.google.com/mail/answer/14257 k2sm211606ioe.19 - gsmtp', u'eventdetectionmcgill@gmail.com')
predict request being processed
Exception on /predict [POST]
Traceback (most recent call last):
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "EventDetectionWebServer.py", line 101, in process_predict
    send_email(user_email, youtube_url, [])
TypeError: send_email() takes exactly 4 arguments (3 given)
predict request being processed
Exception on /predict [POST]
Traceback (most recent call last):
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "EventDetectionWebServer.py", line 101, in process_predict
    send_email(user_email, youtube_url, [])
TypeError: send_email() takes exactly 4 arguments (3 given)
predict request being processed
Exception on /predict [POST]
Traceback (most recent call last):
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "EventDetectionWebServer.py", line 102, in process_predict
    send_email(user_email, youtube_url, [])
TypeError: send_email() takes exactly 4 arguments (3 given)
predict request being processed
Exception on /predict [POST]
Traceback (most recent call last):
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "EventDetectionWebServer.py", line 102, in process_predict
    send_email(user_email, youtube_url, [])
TypeError: send_email() takes exactly 4 arguments (3 given)
predict request being processed
Exception on /predict [POST]
Traceback (most recent call last):
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "EventDetectionWebServer.py", line 102, in process_predict
    send_email(user_email, youtube_url, [])
TypeError: send_email() takes exactly 4 arguments (3 given)
predict request being processed
Exception on /predict [POST]
Traceback (most recent call last):
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "EventDetectionWebServer.py", line 103, in process_predict
    send_email(user_email, youtube_url, [])
TypeError: send_email() takes exactly 4 arguments (3 given)
predict request being processed
Exception on /predict [POST]
Traceback (most recent call last):
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "EventDetectionWebServer.py", line 103, in process_predict
    send_email(user_email, youtube_url, [])
TypeError: send_email() takes exactly 4 arguments (3 given)
predict request being processed
Exception on /predict [POST]
Traceback (most recent call last):
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "EventDetectionWebServer.py", line 103, in process_predict
    send_email(user_email, youtube_url, [])
TypeError: send_email() takes exactly 4 arguments (3 given)
predict request being processed
Exception on /predict [POST]
Traceback (most recent call last):
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "EventDetectionWebServer.py", line 103, in process_predict
    send_email(user_email, youtube_url, [])
TypeError: send_email() takes exactly 4 arguments (3 given)
predict request being processed
Exception on /predict [POST]
Traceback (most recent call last):
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "EventDetectionWebServer.py", line 103, in process_predict
    send_email(user_email, youtube_url, [])
TypeError: send_email() takes exactly 4 arguments (3 given)
predict request being processed
Exception on /predict [POST]
Traceback (most recent call last):
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "EventDetectionWebServer.py", line 103, in process_predict
    send_email(user_email, youtube_url, [])
TypeError: send_email() takes exactly 4 arguments (3 given)
predict request being processed
Exception on /predict [POST]
Traceback (most recent call last):
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "EventDetectionWebServer.py", line 103, in process_predict
    send_email(user_email, youtube_url, [])
TypeError: send_email() takes exactly 4 arguments (3 given)
predict request being processed
Exception on /predict [POST]
Traceback (most recent call last):
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "EventDetectionWebServer.py", line 103, in process_predict
    send_email(user_email, youtube_url, [])
TypeError: send_email() takes exactly 4 arguments (3 given)
predict request being processed
predict request being processed
Exception on /predict [POST]
Traceback (most recent call last):
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "EventDetectionWebServer.py", line 103, in process_predict
    send_email(user_email, youtube_url, ['daniel'])
  File "EventDetectionWebServer.py", line 169, in send_email
    mail.send(msg)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask_mail.py", line 165, in configure_host
    host.login(self.mail.username, self.mail.password)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 622, in login
    raise SMTPAuthenticationError(code, resp)
SMTPAuthenticationError: (454, '4.7.0 Too many login attempts, please try again later. ru8sm9952405igb.2 - gsmtp')
predict request being processed
Exception on /predict [POST]
Traceback (most recent call last):
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "EventDetectionWebServer.py", line 103, in process_predict
    send_email(user_email, youtube_url, ['daniel'])
  File "EventDetectionWebServer.py", line 167, in send_email
    mail.send(msg)
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/Users/danielmacario/.virtualenvs/cv/lib/python2.7/site-packages/flask_mail.py", line 165, in configure_host
    host.login(self.mail.username, self.mail.password)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 622, in login
    raise SMTPAuthenticationError(code, resp)
SMTPAuthenticationError: (454, '4.7.0 Too many login attempts, please try again later. p8sm239083ioe.38 - gsmtp')
predict request being processed
predict request being processed
predict request being processed
predict request being processed
